niwasdekho/login/urls.py
from django.urls import path
from login import views

app_name = 'login'


urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/',views.user_profile,name='profile'),
    path('forgot-pass/',views.forget_pass,name='forgot'),
    path('activate/<uidb64>/<token>/',
        views.activate, name='activate'),


]

niwasdekho/niwasdekho/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from login import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',include('login.urls')),
    path('host_upload/',include('hostupload.urls')),
    path('',views.index,name='index')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

niwasdekho/urls.py
from django.contrib import admin
from django.urls import path
from appbasic import views

app_name = 'appbasic'


urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/',views.user_profile,name='profile'),
    path('upload/',views.Pro_upload,name="upload"),
    path('signup/', views.signup, name='signup'),

    path('activate/<uidb64>/<token>/',
        views.activate, name='activate'),


]

niwasdekho/login/models.py
from django.db import models

from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)
    website = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

niwasdekho/login/forms.py
from login.models import UserProfileInfo
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms



class UserInfoForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput() , label='Confirm password',)
    class Meta:
        model = User
        fields = ['username','email','first_name','password']

    def clean(self):
        cleaned_data = super(UserInfoForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ['profile_pic','website']

niwasdekho/login/views.py
from django.shortcuts import render
from login.forms import UserInfoForm,UserProfileForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from login.models import UserProfileInfo
from django.conf import settings

from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

# Create your views here.
def index(request):
    return render(request,'login/base.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    REGISTERED = False

    if request.method=='POST':

        user_info = UserInfoForm(request.POST)

        if user_info.is_valid() :

            user = user_info.save(commit=False)
            user.set_password(user.password)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('login/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_activation_token.make_token(user),
            })
            to_email = user_info.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()

            REGISTERED=True
            return render(request,'login/register.html',{'user_info':UserInfoForm(),'registered':REGISTERED })
        else:
            print(user_info.errors)
    else:

        user_info = UserInfoForm()

    return render(request,'login/register.html',{'user_info':user_info,'registered':REGISTERED})


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponseRedirect(reverse('index'))
    else:
        return HttpResponse('Activation link is invalid!')
from django.contrib.auth import authenticate,login,logout


def user_login(request):
    CREDENTIALS = False
    USER = True
    if request.method=='POST':

        username = request.POST['username']
        passw = request.POST['password']

        user = authenticate(request , username = username , password = passw)
        ACTIVE = False
        if user:
            USER = False
            CREDENTIALS = True
            if user.is_active:
                login(request,user)
                ACTIVE = True
                return HttpResponseRedirect(reverse('index'))
            else:
                return render(request,'login/user_login.html',{'credentials':CREDENTIALS,'auser':USER})
        else:
            return render(request,'login/user_login.html',{'credentials':CREDENTIALS,'auser':USER})

    else:
        return render(request,'login/user_login.html',{'credentials':CREDENTIALS,'auser':USER})


def forget_pass(request):

    if request.method == 'POST':
        email_id = request.POST['email']
        try:
            user = User.objects.get(email=email_id)
        except(TypeError, ValueError,overflowError, User.DoesNotExist):
            user = None
        if user is not None :
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('login/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()

            return HttpResponse('email is sended to u ')

        else:
            return HttpResponse('you are not registered')

    else:
        return render(request,'login/forgot.html',{})



def user_profile(request):

    if request.user.is_authenticated:
        id = request.user.id
        name_user = request.user.first_name
        path_img = UserProfileInfo.objects.get(user_id=id).profile_pic.url



        dict = {'img_path':path_img,'name':name_user}
        return render(request,'login/profile.html',dict)
    else:
        return HttpResponse("you are not logged in")

niwasdekho/templates/login/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %}
{% endautoescape %}

niwasdekho/templates/login/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% block css %}
    {% endblock %}
    <!-- <link rel="stylesheet" href="{% static "login/css/signup.css"%}"> -->
  </head>
  <body>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSiteName</a>
          </div>
          <ul class="nav navbar-nav">

            <li><a href="{% url 'login:register' %}">register</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'login:logout' %}">logout</a></li>
            {% else %}
            <li><a href="{% url 'login:login' %}">login</a></li>
            {% endif %}
            <li><a href="{% url 'login:profile' %}">profile</a></li>
          </ul>
        </div>
      </nav>

      <div class="container">
        {% block body_block %}
        {% endblock %}

      </div>
  </body>
</html>

niwasdekho/templates/login/forgot.html
{% extends 'login/base.html' %}
{% block body_block %}


<form action="{% url 'login:forgot' %}" method="post">
  {% csrf_token %}
  <input type="email" name="email" placeholder="email">
  <input type="submit" name="submit" value="submit">
</form>

{% endblock %}

niwasdekho/templates/login/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>َLogin Form</title>
    <link rel="stylesheet" href="login.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  </head>
  <body >

<form class="box" action="index.html" method="post">
    <h1 style="color:black">Login</h1>
    <input style="color:black" type="text" onfocus="onFocus()" name="" placeholder="Username" required="">
    <input style="color:black" type="password" name="" placeholder="Password" required="">
    <input style="color:black" type="submit" name="" value="Login">
    <br>
    <div class="rounded-social-buttons">
    <a class="social-button facebook" href="#"></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="social-button google" href="#"></a>
    </div>
    <br><hr><br>
    <a class="active" href="#"  onclick="document.getElementById('modal-wrapper').style.display='block'"><u>forgot password?</u></a><br><br>
    <p style="color:black;">Don' t have an account?</p><br>
    <a href="#" style="color:darkgreen"><span >Register</span></a>
  </form>

  <div id="modal-wrapper" class="modal">
  	<form class="modal-content animate" action="/action_page.php">
  	<div class="container">
  		<span onclick="document,getElementById('modal-wrapper').style.display='none'" class="close" title="close popup">&times;</span>
  	</div>

  <div class="container">
  	  <input  type="email" placeholder="Email" name="uname" required="">
  	  <input onclick="myFunction()" type="submit" name="submit" style="color:black">

  	</div>

  	</form>
  </div>


<script type="text/javascript">
function onFocus() {
  document.getElementById('blur').setAttribute('class', 'blury');
}


var modal=document.getElementById('modal-wrapper');
window.onclick=function(event){
	if(event.target== modal){
		modal.style.display="none";
	}
}

function myFunction() {
    alert("A link has been sent to your email !");
}


</script>


  </body>
</html>

niwasdekho/templates/login/profile.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static "/login/css/profile.css" %}">

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

<div class="container">
  <div class="row">
    <div class="col-md-6 img">
      <img src="{{ img_path }}" alt="not here" class="img-rounded">
    </div>
    <div class="col-md-6 details">
      <blockquote>
        <h5>{{ name }}</h5>
        <h4>{{ img_path }}</h4>
        <small><cite title="Source Title">Chicago, United States of America  <i class="icon-map-marker"></i></cite></small>
      </blockquote>
      <p>
        fionagallager@shameless.com <br>
        www.bootsnipp.com <br>
        June 18, 1990
      </p>
    </div>
  </div>
</div>
  </body>
</html>

niwasdekho/templates/login/register.html
{% extends "login/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'login/css/signup.css' %}">
{% endblock %}
{% block body_block %}

      <div id="myModal" class="modal">
            <div class="modal-content">
            <div class="modal-header">
              <span class="close">&times;</span>
              <h2>Modal Header</h2>
            </div>
            <div class="modal-body">
              <h4>We have sended you an confirmation email</h4>
              <h3>Activate your account!!</h3>
            </div>
            <div class="modal-footer">
              <h3>Modal Footer</h3>
            </div>
            </div>

      </div>
      {% load widget_tweaks %}

      {% if registered %}


        <script>
        // Get the modal
        var modal = document.getElementById('myModal');
        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks the button, open the modal
        window.onload =function() {
            modal.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
            modal.style.display = "none";
        }

        </script>

      {% endif %}
      <form class="box" method="post" action="">
      {% csrf_token %}
      <h1 style="color:black">Signup Form</h1>.

      {{ user_info.username|attr:"placeholder:username"|add_class:"class1" }}
      {% for error in user_info.username.errors %}
           <div >
             {{ error }}
           </div>
      {% endfor %}
      {{ user_info.email|attr:"placeholder:email"|add_class:"class1" }}
      {{ user_info.first_name|attr:"placeholder:Name"|add_class:"class1" }}
      {{ user_info.password|attr:"placeholder:password"|add_class:"class1" }}
      {{ user_info.confirm_password|attr:"placeholder:confirm password"|add_class:"class1" }}
      {% if user_info.errors %}
           <div >
             {{ user_info.errors }}
           </div>
      {% endif %}

      <input style="color:black" type="submit" name="" value="Login">
      <br><br>

      </form>


{% endblock %}

niwasdekho/templates/login/signin.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>َLogin Form</title>
    <link rel="stylesheet" href="style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  </head>
  <body >

<form class="box" action="index.html" method="post">
    <h1 style="color:black">Login</h1>
    <input style="color:black" type="text" onfocus="onFocus()" name="" placeholder="Username" required="">
    <input style="color:black" type="password" name="" placeholder="Password" required="">
    <input onclick="document.getElementById('modal-wrapper1').style.display='block'" style="color:black" type="submit" name="" value="Login">
    <br>
    <div class="rounded-social-buttons">
    <a class="social-button facebook" href="#"></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="social-button google" href="#"></a>
    </div>
    <br><hr><br>
    <a class="active" href="#"  onclick="document.getElementById('modal-wrapper').style.display='block'"><u>forgot password?</u></a><br><br>
    <p style="color:black;">Don' t have an account?</p><br>
    <a href="signup.html" style="color:darkgreen"><span >Register</span></a>
  </form>

  <div id="modal-wrapper" class="modal">
  	<form class="modal-content animate" action="/action_page.php">
  	<div class="container">
  		<span onclick="document,getElementById('modal-wrapper').style.display='none'" class="close" title="close popup">&times;</span>
  	</div>


  <div class="container">
  	  <input  type="email" placeholder="Email" name="uname" required="">
  	  <input onclick="myFunction()" type="submit" name="submit" style="color:black">

  	</div>

  	</form>
  </div>

  <div id="modal-wrapper1" class="modal">
    <form class="modal-content animate" action="/action_page.php">
    <div class="container">
      <span onclick="document,getElementById('modal-wrapper1').style.display='none'" class="close" title="close popup">&times;</span>
    </div>


  <div class="container">
    <br><br>
    <p style="text-align:center;font-size:25px">you have succsessfully logged in</p>

    </div>

    </form>
  </div>




<script type="text/javascript">
function onFocus() {
  document.getElementById('blur').setAttribute('class', 'blury');
}


var modal=document.getElementById('modal-wrapper');
window.onclick=function(event){
	if(event.target== modal){
		modal.style.display="none";
	}
}

if(input.required!=null)
{
  var modal1=document.getElementById('modal-wrapper1');
  window.onclick=function(event){
  	if(event.target== modal1){
  		modal.style.display="none";
  	}
  }
}

function myFunction() {
    alert("A link has been sent to your email !");
}


</script>


  </body>
</html>

niwasdekho/templates/login/user_login.html
{% extends 'login/base.html' %}
{% block body_block %}


<form action="{% url 'login:login' %}" method="post">
  {% csrf_token %}
  <input type="text" name="username" placeholder="username">
  <input type="password" name="password" placeholder="password">

  <input type="submit" name="submit" value="submit">
</form>

{% endblock %}